version: '3.2'
services:
  db-dev:
    image: postgres:11.5
    volumes:
      - type: bind
        source: ./db-data
        target: /var/lib/postgresql/data
    networks:
      - db_net
  api-dev:
    build:
      context: ./backend
      dockerfile: .dev.dockerfile
    volumes:
      - type: bind
        source: ./backend
        target: /code
    networks:
      - api_net
      - db_net
    depends_on:
      - db-dev
  web-dev:
    build:
      context: ./frontend
      dockerfile: .dev.dockerfile
    volumes:
      - type: bind
        source: ./frontend
        target: /code
    networks:
      - web_net
    stdin_open: true
  nginx-dev:
    image: nginx:latest
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf
    ports:
      - 3000:80
    networks:
      - api_net
      - web_net
    depends_on:
      - api-dev
      - web-dev
networks:
  api_net:
  web_net:
  db_net:
